import 'package:brain_rise/services/local_storage_service.dart';

import '../models/achievement_model.dart';
import '../models/lesson_model.dart';
import '../models/questions_model.dart';
import '../models/subject_model.dart';

class QuestionService {
  final LocalStorageService _storage;

  QuestionService(this._storage);

  // Load initial data (for demo app)
  Future<void> loadInitialData() async {
    // Clear existing data first to ensure fresh data is loaded
    await _storage.clearAllData();

    await _loadSubjects();
    await _loadLessons();
    await _loadQuestions();
    await _loadAchievements();
  }

  Future<void> _loadSubjects() async {
    final subjects = _getDemoSubjects();
    await _storage.saveSubjects(subjects);
  }

  Future<void> _loadLessons() async {
    final lessons = _getDemoLessons();
    await _storage.saveLessons(lessons);
  }

  Future<void> _loadQuestions() async {
    final questions = _getDemoQuestions();
    await _storage.saveQuestions(questions);
  }

  Future<void> _loadAchievements() async {
    final achievements = _getDemoAchievements();
    await _storage.saveAchievements(achievements);
  }

  // Demo data generators
  List<Subject> _getDemoSubjects() {
    return [
      Subject(
        id: 'math',
        name: 'Mathematics',
        description: 'Master mathematical concepts and problem-solving',
        iconUrl: '📐',
        category: 'Science',
        examTypes: ['WAEC', 'NECO', 'IELTS'],
        totalLessons: 20,
        color: '#4A90E2',
      ),
      Subject(
        id: 'english',
        name: 'English Language',
        description: 'Improve your grammar, vocabulary, and comprehension',
        iconUrl: '📚',
        category: 'Arts',
        examTypes: ['WAEC', 'NECO', 'IELTS'],
        totalLessons: 20,
        color: '#E94B3C',
      ),
      Subject(
        id: 'physics',
        name: 'Physics',
        description: 'Understand the laws of nature and motion',
        iconUrl: '⚛️',
        category: 'Science',
        examTypes: ['WAEC', 'NECO'],
        totalLessons: 20,
        color: '#9B59B6',
      ),
      Subject(
        id: 'chemistry',
        name: 'Chemistry',
        description: 'Explore matter, reactions, and the periodic table',
        iconUrl: '🧪',
        category: 'Science',
        examTypes: ['WAEC', 'NECO'],
        totalLessons: 20,
        color: '#27AE60',
      ),
      Subject(
        id: 'biology',
        name: 'Biology',
        description: 'Study living organisms and life processes',
        iconUrl: '🧬',
        category: 'Science',
        examTypes: ['WAEC', 'NECO'],
        totalLessons: 20,
        color: '#16A085',
      ),
    ];
  }

  List<Lesson> _getDemoLessons() {
    return [
      // ========== MATHEMATICS (20 Lessons) ==========
      Lesson(
        id: 'math_l1',
        subjectId: 'math',
        title: 'Number Operations',
        description: 'Basic arithmetic and number properties',
        order: 1,
        difficulty: 1,
        questionIds: _getQuestionIds('math', 1),
        xpReward: 15,
        gemsReward: 5,
      ),
      Lesson(
        id: 'math_l2',
        subjectId: 'math',
        title: 'Algebra Basics',
        description: 'Introduction to algebraic expressions and equations',
        order: 2,
        difficulty: 2,
        questionIds: _getQuestionIds('math', 2),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['math_l1'],
      ),
      Lesson(
        id: 'math_l3',
        subjectId: 'math',
        title: 'Fractions & Decimals',
        description: 'Working with fractions and decimal numbers',
        order: 3,
        difficulty: 2,
        questionIds: _getQuestionIds('math', 3),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['math_l1'],
      ),
      Lesson(
        id: 'math_l4',
        subjectId: 'math',
        title: 'Percentages',
        description: 'Understanding and calculating percentages',
        order: 4,
        difficulty: 2,
        questionIds: _getQuestionIds('math', 4),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['math_l1'],
      ),
      Lesson(
        id: 'math_l5',
        subjectId: 'math',
        title: 'Ratios & Proportions',
        description: 'Understanding ratios and proportional relationships',
        order: 5,
        difficulty: 2,
        questionIds: _getQuestionIds('math', 5),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['math_l1'],
      ),
      Lesson(
        id: 'math_l6',
        subjectId: 'math',
        title: 'Geometry Basics',
        description: 'Basic geometric concepts and terms',
        order: 6,
        difficulty: 2,
        questionIds: _getQuestionIds('math', 6),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['math_l1'],
      ),
      Lesson(
        id: 'math_l7',
        subjectId: 'math',
        title: 'Angles & Lines',
        description: 'Types of angles and line relationships',
        order: 7,
        difficulty: 3,
        questionIds: _getQuestionIds('math', 7),
        xpReward: 25,
        gemsReward: 8,
        prerequisiteLessonIds: ['math_l6'],
      ),
      Lesson(
        id: 'math_l8',
        subjectId: 'math',
        title: 'Triangles',
        description: 'Properties and types of triangles',
        order: 8,
        difficulty: 3,
        questionIds: _getQuestionIds('math', 8),
        xpReward: 25,
        gemsReward: 8,
        prerequisiteLessonIds: ['math_l7'],
      ),
      Lesson(
        id: 'math_l9',
        subjectId: 'math',
        title: 'Circles',
        description: 'Circle properties and calculations',
        order: 9,
        difficulty: 3,
        questionIds: _getQuestionIds('math', 9),
        xpReward: 25,
        gemsReward: 8,
        prerequisiteLessonIds: ['math_l6'],
      ),
      Lesson(
        id: 'math_l10',
        subjectId: 'math',
        title: 'Area & Perimeter',
        description: 'Calculating area and perimeter of shapes',
        order: 10,
        difficulty: 3,
        questionIds: _getQuestionIds('math', 10),
        xpReward: 25,
        gemsReward: 8,
        prerequisiteLessonIds: ['math_l6', 'math_l8', 'math_l9'],
      ),
      Lesson(
        id: 'math_l11',
        subjectId: 'math',
        title: 'Word Problems',
        description: 'Solving real-world mathematical problems',
        order: 11,
        difficulty: 3,
        questionIds: _getQuestionIds('math', 11),
        xpReward: 30,
        gemsReward: 10,
        prerequisiteLessonIds: ['math_l2', 'math_l3', 'math_l4'],
      ),
      Lesson(
        id: 'math_l12',
        subjectId: 'math',
        title: 'Statistics',
        description: 'Data representation and analysis',
        order: 12,
        difficulty: 3,
        questionIds: _getQuestionIds('math', 12),
        xpReward: 30,
        gemsReward: 10,
        prerequisiteLessonIds: ['math_l1'],
      ),
      Lesson(
        id: 'math_l13',
        subjectId: 'math',
        title: 'Probability',
        description: 'Understanding chance and likelihood',
        order: 13,
        difficulty: 4,
        questionIds: _getQuestionIds('math', 13),
        xpReward: 30,
        gemsReward: 10,
        prerequisiteLessonIds: ['math_l12'],
      ),
      Lesson(
        id: 'math_l14',
        subjectId: 'math',
        title: 'Integers',
        description: 'Positive and negative numbers',
        order: 14,
        difficulty: 2,
        questionIds: _getQuestionIds('math', 14),
        xpReward: 25,
        gemsReward: 8,
        prerequisiteLessonIds: ['math_l1'],
      ),
      Lesson(
        id: 'math_l15',
        subjectId: 'math',
        title: 'Expressions & Equations',
        description: 'Mathematical expressions and solving equations',
        order: 15,
        difficulty: 3,
        questionIds: _getQuestionIds('math', 15),
        xpReward: 30,
        gemsReward: 10,
        prerequisiteLessonIds: ['math_l2'],
      ),
      Lesson(
        id: 'math_l16',
        subjectId: 'math',
        title: 'Linear Equations',
        description: 'Solving and graphing linear equations',
        order: 16,
        difficulty: 4,
        questionIds: _getQuestionIds('math', 16),
        xpReward: 35,
        gemsReward: 12,
        prerequisiteLessonIds: ['math_l15'],
      ),
      Lesson(
        id: 'math_l17',
        subjectId: 'math',
        title: 'Quadratic Equations',
        description: 'Understanding and solving quadratic equations',
        order: 17,
        difficulty: 4,
        questionIds: _getQuestionIds('math', 17),
        xpReward: 35,
        gemsReward: 12,
        prerequisiteLessonIds: ['math_l16'],
      ),
      Lesson(
        id: 'math_l18',
        subjectId: 'math',
        title: 'Polynomials',
        description: 'Operations with polynomial expressions',
        order: 18,
        difficulty: 4,
        questionIds: _getQuestionIds('math', 18),
        xpReward: 35,
        gemsReward: 12,
        prerequisiteLessonIds: ['math_l15'],
      ),
      Lesson(
        id: 'math_l19',
        subjectId: 'math',
        title: 'Coordinate Geometry',
        description: 'Geometry on the coordinate plane',
        order: 19,
        difficulty: 4,
        questionIds: _getQuestionIds('math', 19),
        xpReward: 40,
        gemsReward: 15,
        prerequisiteLessonIds: ['math_l16'],
      ),
      Lesson(
        id: 'math_l20',
        subjectId: 'math',
        title: 'Trigonometry',
        description: 'Trigonometric ratios and applications',
        order: 20,
        difficulty: 5,
        questionIds: _getQuestionIds('math', 20),
        xpReward: 50,
        gemsReward: 20,
        prerequisiteLessonIds: ['math_l8', 'math_l19'],
      ),

      // ========== ENGLISH LANGUAGE (20 Lessons) ==========
      Lesson(
        id: 'eng_l1',
        subjectId: 'english',
        title: 'Parts of Speech',
        description: 'Nouns, verbs, adjectives, and more',
        order: 1,
        difficulty: 1,
        questionIds: _getQuestionIds('eng', 1),
        xpReward: 15,
        gemsReward: 5,
      ),
      Lesson(
        id: 'eng_l2',
        subjectId: 'english',
        title: 'Subject-Verb Agreement',
        description: 'Matching subjects with correct verb forms',
        order: 2,
        difficulty: 2,
        questionIds: _getQuestionIds('eng', 2),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['eng_l1'],
      ),
      Lesson(
        id: 'eng_l3',
        subjectId: 'english',
        title: 'Tenses',
        description: 'Past, present, and future tenses',
        order: 3,
        difficulty: 2,
        questionIds: _getQuestionIds('eng', 3),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['eng_l1'],
      ),
      Lesson(
        id: 'eng_l4',
        subjectId: 'english',
        title: 'Articles',
        description: 'A, An, The and their usage',
        order: 4,
        difficulty: 2,
        questionIds: _getQuestionIds('eng', 4),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['eng_l1'],
      ),
      Lesson(
        id: 'eng_l5',
        subjectId: 'english',
        title: 'Prepositions',
        description: 'Using prepositions correctly',
        order: 5,
        difficulty: 2,
        questionIds: _getQuestionIds('eng', 5),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['eng_l1'],
      ),
      Lesson(
        id: 'eng_l6',
        subjectId: 'english',
        title: 'Conjunctions',
        description: 'Connecting words and clauses',
        order: 6,
        difficulty: 2,
        questionIds: _getQuestionIds('eng', 6),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['eng_l1'],
      ),
      Lesson(
        id: 'eng_l7',
        subjectId: 'english',
        title: 'Pronouns',
        description: 'Types and usage of pronouns',
        order: 7,
        difficulty: 2,
        questionIds: _getQuestionIds('eng', 7),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['eng_l1'],
      ),
      Lesson(
        id: 'eng_l8',
        subjectId: 'english',
        title: 'Adjectives',
        description: 'Describing nouns with adjectives',
        order: 8,
        difficulty: 2,
        questionIds: _getQuestionIds('eng', 8),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['eng_l1'],
      ),
      Lesson(
        id: 'eng_l9',
        subjectId: 'english',
        title: 'Adverbs',
        description: 'Modifying verbs, adjectives, and other adverbs',
        order: 9,
        difficulty: 2,
        questionIds: _getQuestionIds('eng', 9),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['eng_l1', 'eng_l8'],
      ),
      Lesson(
        id: 'eng_l10',
        subjectId: 'english',
        title: 'Vocabulary',
        description: 'Building and understanding vocabulary',
        order: 10,
        difficulty: 2,
        questionIds: _getQuestionIds('eng', 10),
        xpReward: 25,
        gemsReward: 8,
      ),
      Lesson(
        id: 'eng_l11',
        subjectId: 'english',
        title: 'Synonyms & Antonyms',
        description: 'Words with similar and opposite meanings',
        order: 11,
        difficulty: 2,
        questionIds: _getQuestionIds('eng', 11),
        xpReward: 25,
        gemsReward: 8,
        prerequisiteLessonIds: ['eng_l10'],
      ),
      Lesson(
        id: 'eng_l12',
        subjectId: 'english',
        title: 'Comprehension',
        description: 'Reading and understanding passages',
        order: 12,
        difficulty: 3,
        questionIds: _getQuestionIds('eng', 12),
        xpReward: 30,
        gemsReward: 10,
      ),
      Lesson(
        id: 'eng_l13',
        subjectId: 'english',
        title: 'Letter Writing',
        description: 'Formal and informal letter writing',
        order: 13,
        difficulty: 3,
        questionIds: _getQuestionIds('eng', 13),
        xpReward: 30,
        gemsReward: 10,
      ),
      Lesson(
        id: 'eng_l14',
        subjectId: 'english',
        title: 'Essay Writing',
        description: 'Structuring and writing essays',
        order: 14,
        difficulty: 3,
        questionIds: _getQuestionIds('eng', 14),
        xpReward: 30,
        gemsReward: 10,
        prerequisiteLessonIds: ['eng_l13'],
      ),
      Lesson(
        id: 'eng_l15',
        subjectId: 'english',
        title: 'Summary Writing',
        description: 'Writing concise summaries',
        order: 15,
        difficulty: 3,
        questionIds: _getQuestionIds('eng', 15),
        xpReward: 30,
        gemsReward: 10,
        prerequisiteLessonIds: ['eng_l12'],
      ),
      Lesson(
        id: 'eng_l16',
        subjectId: 'english',
        title: 'Speech',
        description: 'Direct and reported speech',
        order: 16,
        difficulty: 3,
        questionIds: _getQuestionIds('eng', 16),
        xpReward: 30,
        gemsReward: 10,
        prerequisiteLessonIds: ['eng_l3'],
      ),
      Lesson(
        id: 'eng_l17',
        subjectId: 'english',
        title: 'Figures of Speech',
        description: 'Metaphors, similes, and more',
        order: 17,
        difficulty: 3,
        questionIds: _getQuestionIds('eng', 17),
        xpReward: 35,
        gemsReward: 12,
      ),
      Lesson(
        id: 'eng_l18',
        subjectId: 'english',
        title: 'Punctuation',
        description: 'Using punctuation marks correctly',
        order: 18,
        difficulty: 2,
        questionIds: _getQuestionIds('eng', 18),
        xpReward: 25,
        gemsReward: 8,
      ),
      Lesson(
        id: 'eng_l19',
        subjectId: 'english',
        title: 'Direct & Indirect Speech',
        description: 'Converting between speech types',
        order: 19,
        difficulty: 4,
        questionIds: _getQuestionIds('eng', 19),
        xpReward: 35,
        gemsReward: 12,
        prerequisiteLessonIds: ['eng_l16'],
      ),
      Lesson(
        id: 'eng_l20',
        subjectId: 'english',
        title: 'Error Correction',
        description: 'Identifying and correcting errors',
        order: 20,
        difficulty: 4,
        questionIds: _getQuestionIds('eng', 20),
        xpReward: 40,
        gemsReward: 15,
        prerequisiteLessonIds: ['eng_l1', 'eng_l2', 'eng_l3'],
      ),

      // ========== PHYSICS (20 Lessons) ==========
      Lesson(
        id: 'phy_l1',
        subjectId: 'physics',
        title: 'Motion & Speed',
        description: 'Understanding distance, speed, and time',
        order: 1,
        difficulty: 1,
        questionIds: _getQuestionIds('phy', 1),
        xpReward: 15,
        gemsReward: 5,
      ),
      Lesson(
        id: 'phy_l2',
        subjectId: 'physics',
        title: 'Force & Motion',
        description: 'How forces affect motion',
        order: 2,
        difficulty: 2,
        questionIds: _getQuestionIds('phy', 2),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['phy_l1'],
      ),
      Lesson(
        id: 'phy_l3',
        subjectId: 'physics',
        title: 'Newton\'s Laws',
        description: 'Newton\'s three laws of motion',
        order: 3,
        difficulty: 3,
        questionIds: _getQuestionIds('phy', 3),
        xpReward: 25,
        gemsReward: 8,
        prerequisiteLessonIds: ['phy_l2'],
      ),
      Lesson(
        id: 'phy_l4',
        subjectId: 'physics',
        title: 'Work, Energy & Power',
        description: 'Understanding work, energy, and power',
        order: 4,
        difficulty: 3,
        questionIds: _getQuestionIds('phy', 4),
        xpReward: 25,
        gemsReward: 8,
        prerequisiteLessonIds: ['phy_l2'],
      ),
      Lesson(
        id: 'phy_l5',
        subjectId: 'physics',
        title: 'Simple Machines',
        description: 'Levers, pulleys, and inclined planes',
        order: 5,
        difficulty: 3,
        questionIds: _getQuestionIds('phy', 5),
        xpReward: 25,
        gemsReward: 8,
        prerequisiteLessonIds: ['phy_l4'],
      ),
      Lesson(
        id: 'phy_l6',
        subjectId: 'physics',
        title: 'Heat & Temperature',
        description: 'Heat transfer and temperature scales',
        order: 6,
        difficulty: 2,
        questionIds: _getQuestionIds('phy', 6),
        xpReward: 20,
        gemsReward: 7,
      ),
      Lesson(
        id: 'phy_l7',
        subjectId: 'physics',
        title: 'Waves',
        description: 'Properties and types of waves',
        order: 7,
        difficulty: 3,
        questionIds: _getQuestionIds('phy', 7),
        xpReward: 25,
        gemsReward: 8,
      ),
      Lesson(
        id: 'phy_l8',
        subjectId: 'physics',
        title: 'Sound',
        description: 'Sound waves and their properties',
        order: 8,
        difficulty: 3,
        questionIds: _getQuestionIds('phy', 8),
        xpReward: 25,
        gemsReward: 8,
        prerequisiteLessonIds: ['phy_l7'],
      ),
      Lesson(
        id: 'phy_l9',
        subjectId: 'physics',
        title: 'Light',
        description: 'Light properties and behavior',
        order: 9,
        difficulty: 3,
        questionIds: _getQuestionIds('phy', 9),
        xpReward: 25,
        gemsReward: 8,
      ),
      Lesson(
        id: 'phy_l10',
        subjectId: 'physics',
        title: 'Electricity',
        description: 'Electric circuits and components',
        order: 10,
        difficulty: 3,
        questionIds: _getQuestionIds('phy', 10),
        xpReward: 30,
        gemsReward: 10,
      ),
      Lesson(
        id: 'phy_l11',
        subjectId: 'physics',
        title: 'Magnetism',
        description: 'Magnetic fields and forces',
        order: 11,
        difficulty: 3,
        questionIds: _getQuestionIds('phy', 11),
        xpReward: 30,
        gemsReward: 10,
        prerequisiteLessonIds: ['phy_l10'],
      ),
      Lesson(
        id: 'phy_l12',
        subjectId: 'physics',
        title: 'Gravitation',
        description: 'Gravitational force and motion',
        order: 12,
        difficulty: 4,
        questionIds: _getQuestionIds('phy', 12),
        xpReward: 35,
        gemsReward: 12,
        prerequisiteLessonIds: ['phy_l3'],
      ),
      Lesson(
        id: 'phy_l13',
        subjectId: 'physics',
        title: 'Pressure',
        description: 'Pressure in fluids and solids',
        order: 13,
        difficulty: 3,
        questionIds: _getQuestionIds('phy', 13),
        xpReward: 30,
        gemsReward: 10,
      ),
      Lesson(
        id: 'phy_l14',
        subjectId: 'physics',
        title: 'Floating & Sinking',
        description: 'Buoyancy and Archimedes principle',
        order: 14,
        difficulty: 3,
        questionIds: _getQuestionIds('phy', 14),
        xpReward: 30,
        gemsReward: 10,
        prerequisiteLessonIds: ['phy_l13'],
      ),
      Lesson(
        id: 'phy_l15',
        subjectId: 'physics',
        title: 'Machines',
        description: 'Mechanical advantage in machines',
        order: 15,
        difficulty: 4,
        questionIds: _getQuestionIds('phy', 15),
        xpReward: 35,
        gemsReward: 12,
        prerequisiteLessonIds: ['phy_l5'],
      ),
      Lesson(
        id: 'phy_l16',
        subjectId: 'physics',
        title: 'Reflection & Refraction',
        description: 'Light behavior at boundaries',
        order: 16,
        difficulty: 4,
        questionIds: _getQuestionIds('phy', 16),
        xpReward: 35,
        gemsReward: 12,
        prerequisiteLessonIds: ['phy_l9'],
      ),
      Lesson(
        id: 'phy_l17',
        subjectId: 'physics',
        title: 'Modern Physics',
        description: 'Introduction to modern physics concepts',
        order: 17,
        difficulty: 4,
        questionIds: _getQuestionIds('phy', 17),
        xpReward: 40,
        gemsReward: 15,
      ),
      Lesson(
        id: 'phy_l18',
        subjectId: 'physics',
        title: 'Units & Measurements',
        description: 'SI units and measurement techniques',
        order: 18,
        difficulty: 2,
        questionIds: _getQuestionIds('phy', 18),
        xpReward: 20,
        gemsReward: 7,
      ),
      Lesson(
        id: 'phy_l19',
        subjectId: 'physics',
        title: 'Vector & Scalars',
        description: 'Understanding vector and scalar quantities',
        order: 19,
        difficulty: 3,
        questionIds: _getQuestionIds('phy', 19),
        xpReward: 30,
        gemsReward: 10,
      ),
      Lesson(
        id: 'phy_l20',
        subjectId: 'physics',
        title: 'Circular Motion',
        description: 'Motion in circular paths',
        order: 20,
        difficulty: 5,
        questionIds: _getQuestionIds('phy', 20),
        xpReward: 50,
        gemsReward: 20,
        prerequisiteLessonIds: ['phy_l3', 'phy_l12'],
      ),

      // ========== CHEMISTRY (20 Lessons) ==========
      Lesson(
        id: 'chem_l1',
        subjectId: 'chemistry',
        title: 'Atoms & Elements',
        description: 'Basic concepts of atoms, elements, and compounds',
        order: 1,
        difficulty: 1,
        questionIds: _getQuestionIds('chem', 1),
        xpReward: 15,
        gemsReward: 5,
      ),
      Lesson(
        id: 'chem_l2',
        subjectId: 'chemistry',
        title: 'Chemical Bonding',
        description: 'Ionic and covalent bonds',
        order: 2,
        difficulty: 2,
        questionIds: _getQuestionIds('chem', 2),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['chem_l1'],
      ),
      Lesson(
        id: 'chem_l3',
        subjectId: 'chemistry',
        title: 'Compounds',
        description: 'Types and properties of compounds',
        order: 3,
        difficulty: 2,
        questionIds: _getQuestionIds('chem', 3),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['chem_l1'],
      ),
      Lesson(
        id: 'chem_l4',
        subjectId: 'chemistry',
        title: 'Periodic Table',
        description: 'Organization and trends in the periodic table',
        order: 4,
        difficulty: 2,
        questionIds: _getQuestionIds('chem', 4),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['chem_l1'],
      ),
      Lesson(
        id: 'chem_l5',
        subjectId: 'chemistry',
        title: 'States of Matter',
        description: 'Solid, liquid, and gas states',
        order: 5,
        difficulty: 2,
        questionIds: _getQuestionIds('chem', 5),
        xpReward: 20,
        gemsReward: 7,
      ),
      Lesson(
        id: 'chem_l6',
        subjectId: 'chemistry',
        title: 'Mixtures & Separation',
        description: 'Types of mixtures and separation techniques',
        order: 6,
        difficulty: 2,
        questionIds: _getQuestionIds('chem', 6),
        xpReward: 20,
        gemsReward: 7,
      ),
      Lesson(
        id: 'chem_l7',
        subjectId: 'chemistry',
        title: 'Acids, Bases & Salts',
        description: 'Properties and reactions of acids and bases',
        order: 7,
        difficulty: 3,
        questionIds: _getQuestionIds('chem', 7),
        xpReward: 25,
        gemsReward: 8,
      ),
      Lesson(
        id: 'chem_l8',
        subjectId: 'chemistry',
        title: 'Oxidation & Reduction',
        description: 'Oxidation and reduction reactions',
        order: 8,
        difficulty: 3,
        questionIds: _getQuestionIds('chem', 8),
        xpReward: 25,
        gemsReward: 8,
        prerequisiteLessonIds: ['chem_l7'],
      ),
      Lesson(
        id: 'chem_l9',
        subjectId: 'chemistry',
        title: 'Chemical Reactions',
        description: 'Types and characteristics of reactions',
        order: 9,
        difficulty: 3,
        questionIds: _getQuestionIds('chem', 9),
        xpReward: 25,
        gemsReward: 8,
        prerequisiteLessonIds: ['chem_l8'],
      ),
      Lesson(
        id: 'chem_l10',
        subjectId: 'chemistry',
        title: 'Stoichiometry',
        description: 'Calculations in chemical reactions',
        order: 10,
        difficulty: 4,
        questionIds: _getQuestionIds('chem', 10),
        xpReward: 35,
        gemsReward: 12,
        prerequisiteLessonIds: ['chem_l9'],
      ),
      Lesson(
        id: 'chem_l11',
        subjectId: 'chemistry',
        title: 'Gas Laws',
        description: 'Behavior of gases and gas laws',
        order: 11,
        difficulty: 3,
        questionIds: _getQuestionIds('chem', 11),
        xpReward: 30,
        gemsReward: 10,
        prerequisiteLessonIds: ['chem_l5'],
      ),
      Lesson(
        id: 'chem_l12',
        subjectId: 'chemistry',
        title: 'Solutions',
        description: 'Types and properties of solutions',
        order: 12,
        difficulty: 3,
        questionIds: _getQuestionIds('chem', 12),
        xpReward: 30,
        gemsReward: 10,
      ),
      Lesson(
        id: 'chem_l13',
        subjectId: 'chemistry',
        title: 'Electrochemistry',
        description: 'Electrochemical cells and reactions',
        order: 13,
        difficulty: 4,
        questionIds: _getQuestionIds('chem', 13),
        xpReward: 35,
        gemsReward: 12,
        prerequisiteLessonIds: ['chem_l8'],
      ),
      Lesson(
        id: 'chem_l14',
        subjectId: 'chemistry',
        title: 'Chemical Equilibrium',
        description: 'Reversible reactions and equilibrium',
        order: 14,
        difficulty: 4,
        questionIds: _getQuestionIds('chem', 14),
        xpReward: 35,
        gemsReward: 12,
        prerequisiteLessonIds: ['chem_l9'],
      ),
      Lesson(
        id: 'chem_l15',
        subjectId: 'chemistry',
        title: 'Organic Chemistry',
        description: 'Introduction to organic compounds',
        order: 15,
        difficulty: 3,
        questionIds: _getQuestionIds('chem', 15),
        xpReward: 30,
        gemsReward: 10,
      ),
      Lesson(
        id: 'chem_l16',
        subjectId: 'chemistry',
        title: 'Hydrocarbons',
        description: 'Types and properties of hydrocarbons',
        order: 16,
        difficulty: 4,
        questionIds: _getQuestionIds('chem', 16),
        xpReward: 35,
        gemsReward: 12,
        prerequisiteLessonIds: ['chem_l15'],
      ),
      Lesson(
        id: 'chem_l17',
        subjectId: 'chemistry',
        title: 'Polymers',
        description: 'Types and formation of polymers',
        order: 17,
        difficulty: 3,
        questionIds: _getQuestionIds('chem', 17),
        xpReward: 30,
        gemsReward: 10,
        prerequisiteLessonIds: ['chem_l16'],
      ),
      Lesson(
        id: 'chem_l18',
        subjectId: 'chemistry',
        title: 'Environmental Chemistry',
        description: 'Chemistry and the environment',
        order: 18,
        difficulty: 3,
        questionIds: _getQuestionIds('chem', 18),
        xpReward: 30,
        gemsReward: 10,
      ),
      Lesson(
        id: 'chem_l19',
        subjectId: 'chemistry',
        title: 'Chemistry in Industry',
        description: 'Industrial chemical processes',
        order: 19,
        difficulty: 4,
        questionIds: _getQuestionIds('chem', 19),
        xpReward: 40,
        gemsReward: 15,
      ),
      Lesson(
        id: 'chem_l20',
        subjectId: 'chemistry',
        title: 'Chemical Analysis',
        description: 'Methods of chemical analysis',
        order: 20,
        difficulty: 5,
        questionIds: _getQuestionIds('chem', 20),
        xpReward: 50,
        gemsReward: 20,
        prerequisiteLessonIds: ['chem_l14'],
      ),

      // ========== BIOLOGY (20 Lessons) ==========
      Lesson(
        id: 'bio_l1',
        subjectId: 'biology',
        title: 'Cells & Living Things',
        description: 'Introduction to cells and basic biology',
        order: 1,
        difficulty: 1,
        questionIds: _getQuestionIds('bio', 1),
        xpReward: 15,
        gemsReward: 5,
      ),
      Lesson(
        id: 'bio_l2',
        subjectId: 'biology',
        title: 'Cell Structure',
        description: 'Cell organelles and their functions',
        order: 2,
        difficulty: 2,
        questionIds: _getQuestionIds('bio', 2),
        xpReward: 20,
        gemsReward: 7,
        prerequisiteLessonIds: ['bio_l1'],
      ),
      Lesson(
        id: 'bio_l3',
        subjectId: 'biology',
        title: 'Nutrition',
        description: 'Types of nutrition and food groups',
        order: 3,
        difficulty: 2,
        questionIds: _getQuestionIds('bio', 3),
        xpReward: 20,
        gemsReward: 7,
      ),
      Lesson(
        id: 'bio_l4',
        subjectId: 'biology',
        title: 'Respiration',
        description: 'Cellular respiration and gas exchange',
        order: 4,
        difficulty: 3,
        questionIds: _getQuestionIds('bio', 4),
        xpReward: 25,
        gemsReward: 8,
        prerequisiteLessonIds: ['bio_l3'],
      ),
      Lesson(
        id: 'bio_l5',
        subjectId: 'biology',
        title: 'Transport in Plants',
        description: 'Water and nutrient transport in plants',
        order: 5,
        difficulty: 3,
        questionIds: _getQuestionIds('bio', 5),
        xpReward: 25,
        gemsReward: 8,
      ),
      Lesson(
        id: 'bio_l6',
        subjectId: 'biology',
        title: 'Transport in Animals',
        description: 'Circulatory system in animals',
        order: 6,
        difficulty: 3,
        questionIds: _getQuestionIds('bio', 6),
        xpReward: 25,
        gemsReward: 8,
        prerequisiteLessonIds: ['bio_l5'],
      ),
      Lesson(
        id: 'bio_l7',
        subjectId: 'biology',
        title: 'Excretion',
        description: 'Waste removal in living organisms',
        order: 7,
        difficulty: 3,
        questionIds: _getQuestionIds('bio', 7),
        xpReward: 25,
        gemsReward: 8,
      ),
      Lesson(
        id: 'bio_l8',
        subjectId: 'biology',
        title: 'Homeostasis',
        description: 'Maintaining internal balance',
        order: 8,
        difficulty: 3,
        questionIds: _getQuestionIds('bio', 8),
        xpReward: 25,
        gemsReward: 8,
        prerequisiteLessonIds: ['bio_l7'],
      ),
      Lesson(
        id: 'bio_l9',
        subjectId: 'biology',
        title: 'Coordination',
        description: 'Nervous and endocrine systems',
        order: 9,
        difficulty: 3,
        questionIds: _getQuestionIds('bio', 9),
        xpReward: 30,
        gemsReward: 10,
      ),
      Lesson(
        id: 'bio_l10',
        subjectId: 'biology',
        title: 'Reproduction',
        description: 'Types of reproduction in organisms',
        order: 10,
        difficulty: 3,
        questionIds: _getQuestionIds('bio', 10),
        xpReward: 30,
        gemsReward: 10,
      ),
      Lesson(
        id: 'bio_l11',
        subjectId: 'biology',
        title: 'Growth & Development',
        description: 'Growth patterns and development',
        order: 11,
        difficulty: 3,
        questionIds: _getQuestionIds('bio', 11),
        xpReward: 30,
        gemsReward: 10,
        prerequisiteLessonIds: ['bio_l10'],
      ),
      Lesson(
        id: 'bio_l12',
        subjectId: 'biology',
        title: 'Genetics',
        description: 'Heredity and genetic variation',
        order: 12,
        difficulty: 4,
        questionIds: _getQuestionIds('bio', 12),
        xpReward: 35,
        gemsReward: 12,
        prerequisiteLessonIds: ['bio_l11'],
      ),
      Lesson(
        id: 'bio_l13',
        subjectId: 'biology',
        title: 'Evolution',
        description: 'Theory of evolution and evidence',
        order: 13,
        difficulty: 4,
        questionIds: _getQuestionIds('bio', 13),
        xpReward: 35,
        gemsReward: 12,
        prerequisiteLessonIds: ['bio_l12'],
      ),
      Lesson(
        id: 'bio_l14',
        subjectId: 'biology',
        title: 'Ecology',
        description: 'Interactions between organisms and environment',
        order: 14,
        difficulty: 3,
        questionIds: _getQuestionIds('bio', 14),
        xpReward: 30,
        gemsReward: 10,
      ),
      Lesson(
        id: 'bio_l15',
        subjectId: 'biology',
        title: 'Microorganisms',
        description: 'Bacteria, viruses, and fungi',
        order: 15,
        difficulty: 3,
        questionIds: _getQuestionIds('bio', 15),
        xpReward: 30,
        gemsReward: 10,
      ),
      Lesson(
        id: 'bio_l16',
        subjectId: 'biology',
        title: 'Food Production',
        description: 'Agriculture and food security',
        order: 16,
        difficulty: 3,
        questionIds: _getQuestionIds('bio', 16),
        xpReward: 30,
        gemsReward: 10,
        prerequisiteLessonIds: ['bio_l3'],
      ),
      Lesson(
        id: 'bio_l17',
        subjectId: 'biology',
        title: 'Human Body Systems',
        description: 'Major body systems and functions',
        order: 17,
        difficulty: 3,
        questionIds: _getQuestionIds('bio', 17),
        xpReward: 35,
        gemsReward: 12,
        prerequisiteLessonIds: ['bio_l6', 'bio_l7', 'bio_l9'],
      ),
      Lesson(
        id: 'bio_l18',
        subjectId: 'biology',
        title: 'Plant Kingdom',
        description: 'Classification and characteristics of plants',
        order: 18,
        difficulty: 3,
        questionIds: _getQuestionIds('bio', 18),
        xpReward: 30,
        gemsReward: 10,
      ),
      Lesson(
        id: 'bio_l19',
        subjectId: 'biology',
        title: 'Animal Kingdom',
        description: 'Classification and characteristics of animals',
        order: 19,
        difficulty: 3,
        questionIds: _getQuestionIds('bio', 19),
        xpReward: 30,
        gemsReward: 10,
      ),
      Lesson(
        id: 'bio_l20',
        subjectId: 'biology',
        title: 'Health & Disease',
        description: 'Common diseases and prevention',
        order: 20,
        difficulty: 4,
        questionIds: _getQuestionIds('bio', 20),
        xpReward: 40,
        gemsReward: 15,
        prerequisiteLessonIds: ['bio_l15', 'bio_l17'],
      ),
    ];
  }

  // Helper to generate question IDs for each lesson
  List<String> _getQuestionIds(String prefix, int lessonNum) {
    return List.generate(20, (i) => '${prefix}_l${lessonNum}_q${i + 1}');
  }

  List<Question> _getDemoQuestions() {
    final List<Question> questions = [];

    // Generate 20 questions for each of the 20 Math lessons
    for (int lessonNum = 1; lessonNum <= 20; lessonNum++) {
      questions.addAll(_generateMathQuestions(lessonNum));
    }

    // Generate 20 questions for each of the 20 English lessons
    for (int lessonNum = 1; lessonNum <= 20; lessonNum++) {
      questions.addAll(_generateEnglishQuestions(lessonNum));
    }

    // Generate 20 questions for each of the 20 Physics lessons
    for (int lessonNum = 1; lessonNum <= 20; lessonNum++) {
      questions.addAll(_generatePhysicsQuestions(lessonNum));
    }

    // Generate 20 questions for each of the 20 Chemistry lessons
    for (int lessonNum = 1; lessonNum <= 20; lessonNum++) {
      questions.addAll(_generateChemistryQuestions(lessonNum));
    }

    // Generate 20 questions for each of the 20 Biology lessons
    for (int lessonNum = 1; lessonNum <= 20; lessonNum++) {
      questions.addAll(_generateBiologyQuestions(lessonNum));
    }

    return questions;
  }

  // Math question generators - Each lesson has unique questions
  List<Question> _generateMathQuestions(int lessonNum) {
    final lessonId = 'math_l$lessonNum';
    final topics = [
      'Number Operations',
      'Algebra Basics',
      'Fractions & Decimals',
      'Percentages',
      'Ratios & Proportions',
      'Geometry Basics',
      'Angles & Lines',
      'Triangles',
      'Circles',
      'Area & Perimeter',
      'Word Problems',
      'Statistics',
      'Probability',
      'Integers',
      'Expressions & Equations',
      'Linear Equations',
      'Quadratic Equations',
      'Polynomials',
      'Coordinate Geometry',
      'Trigonometry',
    ];
    final topic = topics[lessonNum - 1];

    // Unique question templates for each topic
    final Map<String, List<Map<String, String>>> questionTemplates = {
      'Number Operations': [
        {'q': 'What is 45 + 38?', 'a': '83', 'e': '45 + 38 = 83'},
        {'q': 'What is 12 × 7?', 'a': '84', 'e': '12 × 7 = 84'},
        {'q': 'What is 100 - 47?', 'a': '53', 'e': '100 - 47 = 53'},
        {'q': 'What is 144 ÷ 12?', 'a': '12', 'e': '144 ÷ 12 = 12'},
        {'q': 'What is 25 × 4?', 'a': '100', 'e': '25 × 4 = 100'},
        {'q': 'What is 78 + 22?', 'a': '100', 'e': '78 + 22 = 100'},
        {'q': 'What is 200 - 85?', 'a': '115', 'e': '200 - 85 = 115'},
        {'q': 'What is 15 × 15?', 'a': '225', 'e': '15 × 15 = 225'},
        {'q': 'What is 360 ÷ 6?', 'a': '60', 'e': '360 ÷ 6 = 60'},
        {'q': 'What is 50 + 50?', 'a': '100', 'e': '50 + 50 = 100'},
        {'q': 'What is 99 + 1?', 'a': '100', 'e': '99 + 1 = 100'},
        {'q': 'What is 7 × 12?', 'a': '84', 'e': '7 × 12 = 84'},
        {'q': 'What is 500 - 250?', 'a': '250', 'e': '500 - 250 = 250'},
        {'q': 'What is 18 × 5?', 'a': '90', 'e': '18 × 5 = 90'},
        {'q': 'What is 1000 ÷ 10?', 'a': '100', 'e': '1000 ÷ 10 = 100'},
        {'q': 'What is 33 + 67?', 'a': '100', 'e': '33 + 67 = 100'},
        {'q': 'What is 9 × 11?', 'a': '99', 'e': '9 × 11 = 99'},
        {'q': 'What is 150 - 50?', 'a': '100', 'e': '150 - 50 = 100'},
        {'q': 'What is 20 × 5?', 'a': '100', 'e': '20 × 5 = 100'},
        {'q': 'What is 50 × 2?', 'a': '100', 'e': '50 × 2 = 100'},
      ],
      'Algebra Basics': [
        {
          'q': 'Solve for x: 2x + 5 = 15',
          'a': 'x = 5',
          'e': 'Subtract 5: 2x = 10, divide by 2: x = 5',
        },
        {
          'q': 'Simplify: 3x + 2x',
          'a': '5x',
          'e': 'Combine like terms: 3x + 2x = 5x',
        },
        {
          'q': 'Solve: 4x - 2 = 10',
          'a': 'x = 3',
          'e': 'Add 2: 4x = 12, divide by 4: x = 3',
        },
        {
          'q': 'What is the square root of 144?',
          'a': '12',
          'e': '12 × 12 = 144',
        },
        {'q': 'Solve: x + 8 = 20', 'a': 'x = 12', 'e': 'Subtract 8: x = 12'},
        {'q': 'Simplify: 5x - 2x', 'a': '3x', 'e': '5x - 2x = 3x'},
        {'q': 'Solve: 3x = 21', 'a': 'x = 7', 'e': 'Divide by 3: x = 7'},
        {'q': 'What is 5²?', 'a': '25', 'e': '5² = 5 × 5 = 25'},
        {'q': 'Solve: x - 6 = 10', 'a': 'x = 16', 'e': 'Add 6: x = 16'},
        {'q': 'Simplify: 4x + x', 'a': '5x', 'e': '4x + x = 5x'},
        {
          'q': 'Solve: 2x + 3 = 13',
          'a': 'x = 5',
          'e': 'Subtract 3: 2x = 10, divide by 2: x = 5',
        },
        {'q': 'What is 3³?', 'a': '27', 'e': '3³ = 3 × 3 × 3 = 27'},
        {'q': 'Solve: x/4 = 5', 'a': 'x = 20', 'e': 'Multiply by 4: x = 20'},
        {'q': 'Simplify: 7x - 3x', 'a': '4x', 'e': '7x - 3x = 4x'},
        {
          'q': 'Solve: 5x - 5 = 20',
          'a': 'x = 5',
          'e': 'Add 5: 5x = 25, divide by 5: x = 5',
        },
        {'q': 'What is √81?', 'a': '9', 'e': '9 × 9 = 81'},
        {'q': 'Solve: x + 15 = 30', 'a': 'x = 15', 'e': 'Subtract 15: x = 15'},
        {'q': 'Simplify: 2x + 3x + x', 'a': '6x', 'e': '2x + 3x + x = 6x'},
        {'q': 'Solve: 6x = 36', 'a': 'x = 6', 'e': 'Divide by 6: x = 6'},
        {'q': 'What is 10²?', 'a': '100', 'e': '10² = 100'},
      ],
      'Fractions & Decimals': [
        {'q': 'What is 3/4 + 1/4?', 'a': '1', 'e': '3/4 + 1/4 = 4/4 = 1'},
        {'q': 'What is 2/3 × 6?', 'a': '4', 'e': '2/3 × 6 = 12/3 = 4'},
        {
          'q': 'Convert 0.75 to a fraction',
          'a': '3/4',
          'e': '0.75 = 75/100 = 3/4',
        },
        {'q': 'What is 5 - 1/2?', 'a': '4 1/2', 'e': '5 - 1/2 = 4 1/2'},
        {
          'q': 'What is 3/8 ÷ 2?',
          'a': '3/16',
          'e': '3/8 ÷ 2 = 3/8 × 1/2 = 3/16',
        },
        {
          'q': 'What is 1/2 + 1/4?',
          'a': '3/4',
          'e': '1/2 + 1/4 = 2/4 + 1/4 = 3/4',
        },
        {'q': 'What is 0.5 × 6?', 'a': '3', 'e': '0.5 × 6 = 3'},
        {'q': 'Convert 1/2 to decimal', 'a': '0.5', 'e': '1/2 = 0.5'},
        {'q': 'What is 3/5 × 10?', 'a': '6', 'e': '3/5 × 10 = 30/5 = 6'},
        {'q': 'What is 1 - 3/4?', 'a': '1/4', 'e': '1 - 3/4 = 4/4 - 3/4 = 1/4'},
        {
          'q': 'Convert 0.25 to fraction',
          'a': '1/4',
          'e': '0.25 = 25/100 = 1/4',
        },
        {
          'q': 'What is 2/3 + 1/6?',
          'a': '5/6',
          'e': '2/3 + 1/6 = 4/6 + 1/6 = 5/6',
        },
        {'q': 'What is 0.75 × 4?', 'a': '3', 'e': '0.75 × 4 = 3'},
        {'q': 'What is 5/8 + 3/8?', 'a': '1', 'e': '5/8 + 3/8 = 8/8 = 1'},
        {'q': 'Convert 1/4 to decimal', 'a': '0.25', 'e': '1/4 = 0.25'},
        {'q': 'What is 1/3 × 9?', 'a': '3', 'e': '1/3 × 9 = 9/3 = 3'},
        {'q': 'What is 0.2 × 5?', 'a': '1', 'e': '0.2 × 5 = 1'},
        {'q': 'Convert 2/5 to decimal', 'a': '0.4', 'e': '2/5 = 0.4'},
        {
          'q': 'What is 3/4 - 1/2?',
          'a': '1/4',
          'e': '3/4 - 1/2 = 3/4 - 2/4 = 1/4',
        },
        {'q': 'What is 0.1 × 10?', 'a': '1', 'e': '0.1 × 10 = 1'},
      ],
      'Percentages': [
        {
          'q': 'What is 25% of 80?',
          'a': '20',
          'e': '25% = 25/100 = 1/4, 80 ÷ 4 = 20',
        },
        {
          'q': 'What is 10% of 150?',
          'a': '15',
          'e': '10% = 0.1, 150 × 0.1 = 15',
        },
        {
          'q': 'What is 50% of 200?',
          'a': '100',
          'e': '50% = 0.5, 200 × 0.5 = 100',
        },
        {'q': 'What is 20% of 50?', 'a': '10', 'e': '20% = 0.2, 50 × 0.2 = 10'},
        {
          'q': 'What is 75% of 100?',
          'a': '75',
          'e': '75% = 0.75, 100 × 0.75 = 75',
        },
        {
          'q': 'What is 15% of 200?',
          'a': '30',
          'e': '15% = 0.15, 200 × 0.15 = 30',
        },
        {'q': 'What is 5% of 100?', 'a': '5', 'e': '5% = 0.05, 100 × 0.05 = 5'},
        {'q': 'What is 40% of 80?', 'a': '32', 'e': '40% = 0.4, 80 × 0.4 = 32'},
        {'q': 'What is 60% of 50?', 'a': '30', 'e': '60% = 0.6, 50 × 0.6 = 30'},
        {
          'q': 'What is 30% of 100?',
          'a': '30',
          'e': '30% = 0.3, 100 × 0.3 = 30',
        },
        {'q': 'What is 8% of 50?', 'a': '4', 'e': '8% = 0.08, 50 × 0.08 = 4'},
        {'q': 'What is 12% of 25?', 'a': '3', 'e': '12% = 0.12, 25 × 0.12 = 3'},
        {'q': 'What is 45% of 20?', 'a': '9', 'e': '45% = 0.45, 20 × 0.45 = 9'},
        {'q': 'What is 90% of 10?', 'a': '9', 'e': '90% = 0.9, 10 × 0.9 = 9'},
        {
          'q': 'What is 35% of 40?',
          'a': '14',
          'e': '35% = 0.35, 40 × 0.35 = 14',
        },
        {'q': 'What is 2% of 100?', 'a': '2', 'e': '2% = 0.02, 100 × 0.02 = 2'},
        {
          'q': 'What is 55% of 20?',
          'a': '11',
          'e': '55% = 0.55, 20 × 0.55 = 11',
        },
        {'q': 'What is 70% of 30?', 'a': '21', 'e': '70% = 0.7, 30 × 0.7 = 21'},
        {
          'q': 'What is 25% of 64?',
          'a': '16',
          'e': '25% = 0.25, 64 × 0.25 = 16',
        },
        {'q': 'What is 100% of 99?', 'a': '99', 'e': '100% = 1, 99 × 1 = 99'},
      ],
      'Ratios & Proportions': [
        {
          'q': 'If 3:4 = x:12, what is x?',
          'a': '9',
          'e': '3/4 = x/12, cross multiply: 36 = 4x, x = 9',
        },
        {
          'q': 'Simplify the ratio 10:20',
          'a': '1:2',
          'e': 'Divide both by 10: 10÷10:20÷10 = 1:2',
        },
        {
          'q': 'If 2:5 = 4:x, what is x?',
          'a': '10',
          'e': '2/5 = 4/x, cross multiply: 2x = 20, x = 10',
        },
        {
          'q': 'Simplify the ratio 15:25',
          'a': '3:5',
          'e': 'Divide both by 5: 15÷5:25÷5 = 3:5',
        },
        {
          'q': 'If 1:3 = x:12, what is x?',
          'a': '4',
          'e': '1/3 = x/12, cross multiply: 12 = 3x, x = 4',
        },
        {
          'q': 'Simplify the ratio 8:12',
          'a': '2:3',
          'e': 'Divide both by 4: 8÷4:12÷4 = 2:3',
        },
        {
          'q': 'If 4:7 = 8:x, what is x?',
          'a': '14',
          'e': '4/7 = 8/x, cross multiply: 4x = 56, x = 14',
        },
        {
          'q': 'Simplify the ratio 21:28',
          'a': '3:4',
          'e': 'Divide both by 7: 21÷7:28÷7 = 3:4',
        },
        {
          'q': 'If 5:8 = 10:x, what is x?',
          'a': '16',
          'e': '5/8 = 10/x, cross multiply: 5x = 80, x = 16',
        },
        {
          'q': 'Simplify the ratio 6:9',
          'a': '2:3',
          'e': 'Divide both by 3: 6÷3:9÷3 = 2:3',
        },
        {
          'q': 'If 3:5 = 15:x, what is x?',
          'a': '25',
          'e': '3/5 = 15/x, cross multiply: 3x = 75, x = 25',
        },
        {
          'q': 'Simplify the ratio 16:24',
          'a': '2:3',
          'e': 'Divide both by 8: 16÷8:24÷8 = 2:3',
        },
        {
          'q': 'If 7:9 = 21:x, what is x?',
          'a': '27',
          'e': '7/9 = 21/x, cross multiply: 7x = 189, x = 27',
        },
        {
          'q': 'Simplify the ratio 18:30',
          'a': '3:5',
          'e': 'Divide both by 6: 18÷6:30÷6 = 3:5',
        },
        {
          'q': 'If 2:3 = x:18, what is x?',
          'a': '12',
          'e': '2/3 = x/18, cross multiply: 36 = 3x, x = 12',
        },
        {
          'q': 'Simplify the ratio 14:21',
          'a': '2:3',
          'e': 'Divide both by 7: 14÷7:21÷7 = 2:3',
        },
        {
          'q': 'If 9:11 = 27:x, what is x?',
          'a': '33',
          'e': '9/11 = 27/x, cross multiply: 9x = 297, x = 33',
        },
        {
          'q': 'Simplify the ratio 20:25',
          'a': '4:5',
          'e': 'Divide both by 5: 20÷5:25÷5 = 4:5',
        },
        {
          'q': 'If 4:6 = x:15, what is x?',
          'a': '10',
          'e': '4/6 = x/15, cross multiply: 60 = 6x, x = 10',
        },
        {
          'q': 'Simplify the ratio 12:18',
          'a': '2:3',
          'e': 'Divide both by 6: 12÷6:18÷6 = 2:3',
        },
      ],
    };

    final templates = questionTemplates[topic] ?? [];

    return List.generate(20, (i) {
      final qNum = i + 1;
      final template = i < templates.length
          ? templates[i]
          : {
              'q': 'What is ${10 + i * 5} + ${20 + i * 5}?',
              'a': '${30 + i * 10}',
              'e': 'Basic arithmetic',
            };
      return Question(
        id: 'math_l${lessonNum}_q$qNum',
        lessonId: lessonId,
        questionText: template['q']!,
        type: QuestionType.multipleChoice,
        options: _generateMathOptions(template['a']!, qNum),
        correctAnswer: template['a']!,
        explanation: template['e']!,
        difficulty: ((lessonNum - 1) ~/ 4 + 1).clamp(1, 5),
        timeLimit: 30 + (qNum * 2),
        tags: [topic.toLowerCase().replaceAll(' ', '_'), 'math'],
      );
    });
  }

  // Helper to generate unique options for math
  List<String> _generateMathOptions(String correctAnswer, int seed) {
    final answerNum =
        int.tryParse(correctAnswer.replaceAll(RegExp(r'[^0-9]'), '')) ?? 10;
    final base = answerNum + seed * 7;
    return [
      correctAnswer,
      '${base % 100}',
      '${(base + 5) % 100}',
      '${(base + 10) % 100}',
    ];
  }

  // English question generators
  List<Question> _generateEnglishQuestions(int lessonNum) {
    final lessonId = 'eng_l$lessonNum';
    final topics = [
      'Parts of Speech',
      'Subject-Verb Agreement',
      'Tenses',
      'Articles',
      'Prepositions',
      'Conjunctions',
      'Pronouns',
      'Adjectives',
      'Adverbs',
      'Vocabulary',
      'Synonyms & Antonyms',
      'Comprehension',
      'Letter Writing',
      'Essay Writing',
      'Summary Writing',
      'Speech',
      'Figures of Speech',
      'Punctuation',
      'Direct & Indirect Speech',
      'Error Correction',
    ];
    final topic = topics[lessonNum - 1];
    return List.generate(20, (i) {
      final qNum = i + 1;
      return Question(
        id: 'eng_l${lessonNum}_q$qNum',
        lessonId: lessonId,
        questionText: 'Sample English question $qNum on $topic',
        type: QuestionType.multipleChoice,
        options: _generateOptions(qNum),
        correctAnswer: 'Option ${(qNum % 4) + 1}',
        explanation:
            'The correct answer is Option ${(qNum % 4) + 1} for this $topic question',
        difficulty: ((lessonNum - 1) ~/ 4 + 1).clamp(1, 5),
        timeLimit: 30 + (qNum * 2),
        tags: [topic.toLowerCase().replaceAll(' ', '_'), 'english'],
      );
    });
  }

  // Physics question generators
  List<Question> _generatePhysicsQuestions(int lessonNum) {
    final lessonId = 'phy_l$lessonNum';
    final topics = [
      'Motion & Speed',
      'Force & Motion',
      "Newton's Laws",
      'Work, Energy & Power',
      'Simple Machines',
      'Heat & Temperature',
      'Waves',
      'Sound',
      'Light',
      'Electricity',
      'Magnetism',
      'Gravitation',
      'Pressure',
      'Floating & Sinking',
      'Machines',
      'Reflection & Refraction',
      'Modern Physics',
      'Units & Measurements',
      'Vector & Scalars',
      'Circular Motion',
    ];
    final topic = topics[lessonNum - 1];
    return List.generate(20, (i) {
      final qNum = i + 1;
      return Question(
        id: 'phy_l${lessonNum}_q$qNum',
        lessonId: lessonId,
        questionText: 'Sample physics question $qNum on $topic',
        type: QuestionType.multipleChoice,
        options: _generateOptions(qNum),
        correctAnswer: 'Option ${(qNum % 4) + 1}',
        explanation: 'The answer demonstrates the principle of $topic',
        difficulty: ((lessonNum - 1) ~/ 4 + 1).clamp(1, 5),
        timeLimit: 30 + (qNum * 2),
        tags: [topic.toLowerCase().replaceAll(' ', '_'), 'physics'],
      );
    });
  }

  // Chemistry question generators
  List<Question> _generateChemistryQuestions(int lessonNum) {
    final lessonId = 'chem_l$lessonNum';
    final topics = [
      'Atoms & Elements',
      'Chemical Bonding',
      'Compounds',
      'Periodic Table',
      'States of Matter',
      'Mixtures & Separation',
      'Acids, Bases & Salts',
      'Oxidation & Reduction',
      'Chemical Reactions',
      'Stoichiometry',
      'Gas Laws',
      'Solutions',
      'Electrochemistry',
      'Chemical Equilibrium',
      'Organic Chemistry',
      'Hydrocarbons',
      'Polymers',
      'Environmental Chemistry',
      'Chemistry in Industry',
      'Chemical Analysis',
    ];
    final topic = topics[lessonNum - 1];
    return List.generate(20, (i) {
      final qNum = i + 1;
      return Question(
        id: 'chem_l${lessonNum}_q$qNum',
        lessonId: lessonId,
        questionText: 'Sample chemistry question $qNum on $topic',
        type: QuestionType.multipleChoice,
        options: _generateOptions(qNum),
        correctAnswer: 'Option ${(qNum % 4) + 1}',
        explanation: 'This demonstrates the concept of $topic in chemistry',
        difficulty: ((lessonNum - 1) ~/ 4 + 1).clamp(1, 5),
        timeLimit: 30 + (qNum * 2),
        tags: [topic.toLowerCase().replaceAll(' ', '_'), 'chemistry'],
      );
    });
  }

  // Biology question generators
  List<Question> _generateBiologyQuestions(int lessonNum) {
    final lessonId = 'bio_l$lessonNum';
    final topics = [
      'Cells & Living Things',
      'Cell Structure',
      'Nutrition',
      'Respiration',
      'Transport in Plants',
      'Transport in Animals',
      'Excretion',
      'Homeostasis',
      'Coordination',
      'Reproduction',
      'Growth & Development',
      'Genetics',
      'Evolution',
      'Ecology',
      'Microorganisms',
      'Food Production',
      'Human Body Systems',
      'Plant Kingdom',
      'Animal Kingdom',
      'Health & Disease',
    ];
    final topic = topics[lessonNum - 1];
    return List.generate(20, (i) {
      final qNum = i + 1;
      return Question(
        id: 'bio_l${lessonNum}_q$qNum',
        lessonId: lessonId,
        questionText: 'Sample biology question $qNum on $topic',
        type: QuestionType.multipleChoice,
        options: _generateOptions(qNum),
        correctAnswer: 'Option ${(qNum % 4) + 1}',
        explanation: 'This relates to the biological concept of $topic',
        difficulty: ((lessonNum - 1) ~/ 4 + 1).clamp(1, 5),
        timeLimit: 30 + (qNum * 2),
        tags: [topic.toLowerCase().replaceAll(' ', '_'), 'biology'],
      );
    });
  }

  // Helper to generate multiple choice options
  List<String> _generateOptions(int seed) {
    final base = seed * 7;
    return [
      'Option ${(base % 4) + 1}',
      'Option ${(base + 1) % 4 + 1}',
      'Option ${(base + 2) % 4 + 1}',
      'Option ${(base + 3) % 4 + 1}',
    ];
  }

  List<Achievement> _getDemoAchievements() {
    return [
      Achievement(
        id: 'streak_3',
        title: 'Getting Started',
        description: 'Maintain a 3-day streak',
        iconUrl: '🔥',
        type: AchievementType.streak,
        targetValue: 3,
        gemsReward: 10,
      ),
      Achievement(
        id: 'streak_7',
        title: 'Week Warrior',
        description: 'Maintain a 7-day streak',
        iconUrl: '⭐',
        type: AchievementType.streak,
        targetValue: 7,
        gemsReward: 25,
      ),
      Achievement(
        id: 'questions_50',
        title: 'Question Master',
        description: 'Answer 50 questions correctly',
        iconUrl: '🎯',
        type: AchievementType.questionsAnswered,
        targetValue: 50,
        gemsReward: 15,
      ),
      Achievement(
        id: 'lessons_10',
        title: 'Learning Machine',
        description: 'Complete 10 lessons',
        iconUrl: '📖',
        type: AchievementType.lessonsCompleted,
        targetValue: 10,
        gemsReward: 20,
      ),
      Achievement(
        id: 'perfect_5',
        title: 'Perfectionist',
        description: 'Get perfect scores on 5 lessons',
        iconUrl: '💯',
        type: AchievementType.perfectScore,
        targetValue: 5,
        gemsReward: 30,
      ),
    ];
  }

  // Check if initial data is loaded
  Future<bool> isDataLoaded() async {
    final subjects = await _storage.getAllSubjects();
    return subjects.isNotEmpty;
  }
}
